# 项目相关配置
ruoyi:
  # 名称
  name: Activiti
  # 版本
  version: 3.8.1
  # 版权年份
  copyrightYear: 2022
  # 实例演示开关
  demoEnabled: true
  # 文件路径 示例（ Windows配置D:/ruoyi/uploadPath，Linux配置 /home/ruoyi/uploadPath）
  profile: D:\ruoyi\uploadPath
  # 获取ip地址开关
  addressEnabled: false
  # 验证码类型 math 数组计算 char 字符验证
  captchaType: math

# 开发环境配置
server:
  # 服务器的HTTP端口，默认为8080
  port: 9080
  servlet:
    # 应用的访问路径
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # 连接数满后的排队数，默认为100
    accept-count: 1000
    threads:
      # tomcat最大线程数，默认为200
      max: 800
      # Tomcat启动初始化的线程数，默认值10
      min-spare: 100

# 日志配置
logging:
  level:
    com.ruoyi: debug
    org.springframework: warn

# Spring配置
spring:
  jackson:
    default-property-inclusion: always
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: i18n/messages
  profiles:
    active: druid
  # 文件上传
  servlet:
    multipart:
      # 单个文件大小
      max-file-size: 10MB
      # 设置总上传的文件大小
      max-request-size: 20MB
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true
  # redis 配置
  redis:
    # 地址
    host: 192.168.200.130
    #    host: 127.0.0.1
    # 端口，默认为6379
    port: 6379
    # 数据库索引
    database: 1
    # 密码
    password:
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms

# token配置
token:
  # 令牌自定义标识
  header: Authorization
  # 令牌密钥
  secret: abcdefghijklmnopqrstuvwxyz
  # 令牌有效期（默认30分钟）
  expireTime: 600

# MyBatis配置
#mybatis:
#    # 搜索指定包别名
#    typeAliasesPackage: com.ruoyi.**.domain
#    # 配置mapper的扫描，找到所有的mapper.xml映射文件
#    mapperLocations: classpath*:mapper/**/*Mapper.xml
#    # 加载全局的配置文件
#    configLocation: classpath:mybatis/mybatis-config.xml

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  type-aliases-package: com.ruoyi.**.domain
  global-config:
    # 逻辑删除配置
    db-config:
      # 删除前
      logic-not-delete-value: 0
      # 删除后
      logic-delete-value: 1

# PageHelper分页插件
pagehelper:
  helperDialect: mysql
  supportMethodsArguments: false
  params: count=countSql

# Swagger配置
swagger:
  # 是否开启swagger
  enabled: true
  # 请求前缀
  pathMapping:

# 防止XSS攻击
xss:
  # 过滤开关
  enabled: true
  # 排除链接（多个用逗号分隔）
  excludes: /system/notice
  # 匹配链接
  urlPatterns: /system/*,/monitor/*,/tool/*

#支付相关
ali:
  pay:
    #应用ID,您的APPID，收款账号既是您的APPID对应支付宝账号
    appid: 2021003125681491
    #商户私钥，您的PKCS8格式RSA2私钥
    privateKey: MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCANfA3i8m8nfs+UUGU7qZNLlpK/8MRWOATIVMW06NrolWkX9GGjvg1mke7sudp+mKGR3D7EM9eH9ncfWr5GtFevADByWlAk3UAmtIHYXLJo9j9Bp8n41QXS8OeUVGnoQ7RmBItegk01iPZXLrIeEBM5g9VCfLl/E+xjTnRRNLSjM0+y1ieGYoJlZE6Oqbxl5vb2GoI7uJFnuzgvM18KOdhYjyilAbVqpEu3HuhrWlPcsgTXylIxHqMiAxs4uhHaqWOjLqxL7QSsMdOcOguw5Fx9mOaHapZQZT/1q2Gl2ptwfpGeQhljErgUbUnWw0pWYvrgOfHfx0M43H601avKn4dAgMBAAECggEAOC1qMCyEHK1sZQXdopBfNfpVff9LTdKPfFJhweLB/GuI8xk5CaijgXk0bT4awAkCGqw7CQd4lVmHcGFT+gqSKtxdyIukHrN91OIBnVJJpaixb0zzd9rYAc0kzb379WNQxu3HKT4LwqcB1kAXZ7epFQjJNw3A7Jz9nmKvLs7lQXPomb2nh421lHhhz1rKKQT5JiAnxEzak9lVr455iy50qEtYyU7uEAuIsAglXQeaXFdOn3y/wuLak7BDbKrS+CKRcbpbEAqAa6nzQ6LYyFGJeQYG0kztw9sZYRczBK6M/tcAKg43/H8gVYdbPr0JqBViK4jkzXMldeRakUBko/lQgQKBgQDMmtm31aUE/G43k4JaXIyRs0RpQ9S1qULbPuFdXGy3bhEmdNFMmCic2Fx0k22OOnyWTNfp/G1eXfA+cI4aWYKWNzIpwOasjTFHdIQSwfwOmDTihwa5YEmw+4JpKS2uqv7imU6wLnjeOnPKSgZSxQn49YYWbx5taTNgl/T6Hccc2QKBgQCgaowqT6pIxG0mu1NnnSVECsFPN4c7MHRgAQf3i1HsWd+k2MlUgz5WXrHCnU6Wr/V9kBTt7SQ/Gw/XtmIAbrsUQnWEixrq3hdGrMLk8buxHSgrYbifBRW6Cz3xdRzWIu+awGZ76/wYfEpjDeWS3v0AiNWM7eYQBJgi4Xgk+K0w5QKBgETEiwaRpQwe98BwMLDESG60DPtAVB7Wi+T6pm5loRipwtPlEW+n+IZ25eQ8pObX24X8v9kiAXRlKFkkJW7PxOdOF+sWrbEzJ2v3ymgvkNMq7yNv9J+bsEjuz68eqv749AAfPOZUSEWQ6dgEt0lcdnSZuP6TTGvDnwQJLspd9c1JAoGAJolyIrgAsHp/vk5COyIFUdNDnUQ5uH5rdqTIxS8y/xSYJYHu296rmxQkoBwqRQkAcKmsXXwauQ5HQAsQgAoZ50QP90dzr/iqns/iAh4QePwIKmPPdmRCU+9fciIwS0EZTpPqCtsmNLunIySzghUPspEsvC5qlm6EHd0Mf9U9xgECgYBYbxpcaNLT33ftdZNJzyrbnwfvAjiv2LbrN/5DCj02nEwUmM4YU1wuEh3cmhnhb+EWBIzJVExIEXyQJZe4UbRC0gDTd4xwQ/QryPSdxOPJ7uaRYrYBjeM8qOBTbgTApWWJWCBJJWc/vQ9aSYzurKnHKOn9R4K/qaREskPov/Q3Ag==
    #//支付宝公钥,查看地址：https://openhome.alipay.com/platform/keyManage.htm 对应APPID下的支付宝公钥。
    publicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAto0cQba6DZb5r4ZKk86ZYNuKLu4mqd10ax9M+c0iS2Ilt/fx7Ih2kP8mtOHWwxrPe02qY500H3ioKcp21DFzW2lhq7wBGbyKaEPYeg61UIRKxxT0NxCcqvwwWCH4jo6ziQIiGaV68AxTTw3wEva5A68759UW/6Ecl3KQWJ4XqfcjWy94zFBpeQHDIDoXxfHNhuVjoTffXiNj+E23ZbvJHOlTYHJ1N5nNhLWOvCbTByg51ICDRKjY5CYKQcSLYK31Czwfhtc6BkQJUflLQKpmhXRA/i2K5r10cBkYog7QsDl1gwxnAZswuYet2Qqysq/sfVTgyh93XKtZu+53j7WgRQIDAQAB
    inputCharset: UTF-8
    signType: RSA2
    gateway:
      url: https://openapi.alipay.com/gateway.do
wechat:
  pay:
    #秘钥
    #    key: b56e7523014247276e765e2e3ba89e86
    key: Rxkjhbxa20051991133100MA0EY47M0T
    #小程序 appid
    appletAppId: wx1dc17a6c0e48fafd
    #小程序商户 id
    appletMchId: 1577959261
    #app AppId
    appId: wxbb004b56371dc84b
    #app 商户Id
    appMchId: 1624969344
    #公众号 Appid
    subscriptionAppId: wxd4a72ec084e73ebd
    #公众号 商户id
    subscriptionMchId: 1624969344
    #H5 Appid
    h5AppId: wxbb004b56371dc84b
    # h5 商户id
    h5MchId: 1624969344
    # 证书地址
    certName: apiclient_cert.p12
unionpay:
  encoding: UTF-8
  frontUrl:
    app: https://www.d-eg.com/share/yunPayCallBack.html
    web: https://www.d-eg.com/#/my/order
  signCert:
    qrMerId: 777290058198285
    qrPath: /unionpay/qr_sign.pfx
    applePayMerId: 777290058198285
    applePayPath: /unionpay/apple_pay_sign.pfx
    wapMerId: 777290058198285
    wapPath: /unionpay/wap_sign.pfx

callBack:
  notifyUrl: http://wisdom.vaiwan.com/balanceCallBack/notifyUrl/%s
  returnUrl: https://www.d-eg.com/#/my/order
